FROM alpine:3.7 

RUN apk add --no-cache wget && \
    wget https://github.com/progrium/entrykit/releases/download/v0.4.0/entrykit_0.4.0_Linux_x86_64.tgz && \
    tar -xvzf entrykit_0.4.0_Linux_x86_64.tgz && \
    rm entrykit_0.4.0_Linux_x86_64.tgz && \
    mv entrykit /bin/entrykit && \
    chmod +x /bin/entrykit && \
    entrykit --symlink
